package ru.vital.daily.enums;

public final class Operation {

    public static final String ACTION_MESSAGE_SEND = "ACTION_MESSAGE_SEND",
            ACTION_MESSAGE_SEND_UPDATED = "ACTION_MESSAGE_SEND_UPDATED",
            ACTION_MESSAGE_CANCEL = "ACTION_MESSAGE_CANCEL",
            ACTION_MESSAGE_DELETE = "ACTION_MESSAGE_DELETE",
            ACTION_MESSAGE_CHANGE = "ACTION_MESSAGE_CHANGE",
            ACTION_MESSAGE_SEND_FAILED = "ACTION_MESSAGE_SEND_FAILED",
            ACTION_MESSAGE_TYPE = "ACTION_MESSAGE_TYPE",
            ACTION_MESSAGE_READ = "ACTION_MESSAGE_READ",
            ACTION_MESSAGE_FIND = "ACTION_MESSAGE_FIND",

            ACTION_PROFILE_ONLINE = "ACTION_PROFILE_ONLINE",

            ACTION_JOB_DELETE = "ACTION_JOB_DELETE",

            ACTION_MEDIA_CHANGE = "ACTION_MEDIA_CHANGE",

            ACTION_MEDIA_DOWNLOAD_START = "ACTION_MEDIA_DOWNLOAD_START",
            ACTION_MEDIA_DOWNLOAD_PROGRESS = "ACTION_MEDIA_DOWNLOAD_PROGRESS",
            ACTION_MEDIA_DOWNLOAD_SUCCESS = "ACTION_MEDIA_DOWNLOAD_SUCCESS",
            ACTION_MEDIA_DOWNLOAD_CANCEL = "ACTION_MEDIA_DOWNLOAD_CANCEL",

            ACTION_MEDIA_UPLOAD_PROGRESS = "ACTION_MEDIA_UPLOAD_PROGRESS",
            ACTION_MEDIA_UPLOAD_FAILED = "ACTION_MEDIA_UPLOAD_FAILED",
            ACTION_MEDIA_UPLOAD_SUCCESS = "ACTION_MEDIA_UPLOAD_SUCCESS",
            ACTION_MEDIA_UPLOAD_START = "ACTION_MEDIA_UPLOAD_START",
            ACTION_MEDIA_UPLOAD_END = "ACTION_MEDIA_UPLOAD_END",
            ACTION_MEDIA_UPLOAD_CANCEL = "ACTION_MEDIA_UPLOAD_CANCEL",

            ACTION_INTERNET_ONLINE = "ACTION_INTERNET_ONLINE",
            ACTION_INTERNET_OFFLINE = "ACTION_INTERNET_OFFLINE";

}
